### ISSUE TITLE
all-test fails on pgf/clip-multi.pdf

### ISSUE THREAD

**Issue by byorgey** [diagrams/diagrams-backend-tests#5]
```
Error: /undefinedfilename in (pgf/clip-multi.pdf)
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push
Dictionary stack:
   --dict:1199/1684(ro)(G)--   --dict:0/20(G)--   --dict:78/200(L)--
Current allocation mode is local
Last OS error: No such file or directory
GPL Ghostscript 9.18: Unrecoverable error, exit code 1
all-test: Image 2 not read
```

**Comment by byorgey** [comment]
@cchalmers do you have any ideas what might be going on here?

**Comment by byorgey** [comment]
`clip-multi` is a red herring, that just happened to be the first test where there wasn't an existing `.pdf` output left over from the last time I ran the backend tests.  Something is going wrong so the pgf outputs aren't getting converted to pdf.

**Comment by cchalmers** [comment]
Not sure but you're using a newer version of ghostscript that me. Maybe using `-o` instead of `-sOutputFile` (found [here](http://stackoverflow.com/questions/27454350/ghostscript-unrecoverable-error-undefinedfilename-in-setpagedevice)) works?

**Comment by byorgey** [comment]
I figured it out --- since the pgf backend can now emit PDF directly I just had it do that.  There was no step in the tester to convert the .tex output to .pdf.  Honestly I'm not quite sure how it ever worked before.  Oh well, it works perfectly now!
